config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs do
    collection do
      get :search
    end
    resources :resumes
  end

  namespace :account do
    resources :jobs
  end

  namespace :admin do
    namespace :account do
      resources :jobs do
        member do
          post :publish
          post :hide
        end

        resources :resumes
      end
    end
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
    resources :categories
  end
  root 'welcome#index'
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: { message: "请填写概念名称" }
  validates :description, presence: { message: "请填写概念描述" }
  validates :company_name, presence: { message: "请填写践行标准" }
  validates :category_name, presence: { message: "请选择践行城市" }
  validates :wage_upper_bound, presence: { message: "请填写最低践行时长" }
  validates :wage_lower_bound, presence: { message: "请填写最高践行时长" }
  validates :wage_lower_bound, numericality: { greater_than: 0, message: "最小践行天数必须＞0" }
  validates :wage_lower_bound, numericality: { less_than: :wage_upper_bound, message: "践行时段下限不能高于践行时段上限" }
  validates :contact_email, presence: { message: "请填写联系邮箱" }

# 最大薪资必须大于最小薪资

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  scope :publish, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }

  has_many :resumes
  belongs_to :category
  belongs_to :user

  has_many :job_relationships
  has_many :members, through: :job_relationships, source: :user
end

app/controllers/account/jobs_controller.rb
class Account::JobsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_is_not_admin

	def index
		@jobs = current_user.participated_jobs.paginate(:page => params[:page], :per_page => 10)
	end
end

app/controllers/admin/account/jobs_controller.rb
class Admin::Account::JobsController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :require_is_admin

  layout "admin"

  def index
    @jobs = current_user.jobs.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      redirect_to admin_jobs_path, alert: "概念已隐藏，无法查阅了，你想清楚就好！"
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "概念更新成功！这年头必须随时更新自己脑子里面的概念！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path, alert: "概念已删除了，你后悔吗？"
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :company_name, :wage_upper_bound, :wage_lower_bound, :contact_email, :category_name)
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :require_is_super_admin, only: [:new, :edit, ]

  layout "admin"

  def index
    @jobs = Job.all.recent.paginate(:page => params[:page], :per_page => 15)
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      redirect_to admin_account_jobs_path, alert: "概念已隐藏，无法查阅，你想清楚就好！"
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to admin_account_jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_account_jobs_path, notice: "概念更新成功！这年头必须随时更新自己脑子里面的概念！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_account_jobs_path, alert: "概念已删除，如果后悔赶紧做个提取练习试试！快去，我等你！"
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :company_name, :wage_upper_bound, :wage_lower_bound, :contact_email, :category_name)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :validate_search_key, :only => [:search]

  def index
    @jobs = case params[:order]
            when 'by_lower_bound'
              Job.publish.order('wage_lower_bound').paginate(:page => params[:page], :per_page => 10)
            when 'by_upper_bound'
              Job.publish.order('wage_upper_bound').paginate(:page => params[:page], :per_page => 10)
            else
              Job.publish.recent.paginate(:page => params[:page], :per_page => 10)
            end
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "不好意思概念已隐藏！"
      redirect_to root_path
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path, notice: "当你看到这段文字时，代表着你成功升级了，但离财富自由还有100000光年，加油！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path, alert: "恭喜你做了舍弃行为！这年头放弃安全感真的不容易啊！"
  end

  def search
    if @query_string.present?
      search_result = Job.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.paginate(:page => params[:page], :per_page => 15 )
      puts @jobs
    else
      @jobs = Job.publish.recent.paginate(:page => params[:page], :per_page => 10)
      puts @jobs
    end
  end

  private

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    { :title_or_description_or_contact_email_or_location_or_company_name_or_category_name_cont => query_string }
  end

  def job_params
    params.require(:job).permit(:title, :description, :company_name, :wage_upper_bound, :wage_lower_bound, :contact_email)
  end
end

app/helpers/account/jobs_helper.rb
module Account::JobsHelper
end

app/helpers/admin/account/jobs_helper.rb
module Admin::Account::JobsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_description(job)
		simple_format(job.description)
	end
end

app/views/jobs/_item.erb
<div class="list_item clearfix">
  <div class="left fl">
    <div class="position_name clearfix">
      <h2 class="fl"><%= link_to(job.title, job_path(job)) %></h2>
      <span class="fl"><%= sliceDate(job) %>发布</span>
    </div>
    <div class="salary"><%= job.wage_lower_bound %>
      -
      <%= job.wage_upper_bound %></div>
  </div>
</div>

app/views/jobs/_resume_btn.html.erb
<% if current_user && current_user.is_member_of?(job) %>
<%= link_to("已申请", '#', class: "btn btn-default btn-xs disabled") %>
<% else %>
<%= link_to("马上申请践行", new_job_resume_path(job), class: "btn btn-success btn-xs") %>
<% end %>

app/views/jobs/_search_bar.html.erb
<%= form_tag search_jobs_path , :method => :get, :class => "jobs-search-form" do %>
<div class="input-group">
  <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="搜索概念关键字...">

  <span class="input-group-btn">
    <button type="submit" class="btn btn-default">
      <span class="glyphicon glyphicon-search"></span>
    </button>
  </span>
</div>
<% end %>

app/views/jobs/edit.html.erb
<div class="container">
  <h1>
    编辑概念
  </h1>
  <hr/>

  <%= simple_form_for @job do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "概念名称", input_html: { class: "form-control"} %>
    <%= f.input :description, :label => "概念内容", input_html: { class: "form-control"} %>
    <%= f.input :company_name, :label => "践行标准", input_html: { class: "form-control"} %>
    <%= f.input :wage_lower_bound, :label => "最高践行时长", input_html: { class: "form-control"} %>
    <%= f.input :wage_upper_bound, :label => "最低践行时长", input_html: { class: "form-control"} %>
    <%= f.input :contact_email, :label => "联系邮箱", input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="jobs-container">
    <div class="content">
      <ul class="nav nav-tabs">
        <li class="<%= 'active' if !params[:order] %>">
          <%= link_to("默认排序", jobs_path) %>
        </li>
        <li <li class="<%= 'active' if params[:order] == 'by_lower_bound' %>"> <%= link_to("按最低践行时段排序", jobs_path(:order => "by_lower_bound" )) %></li>
        <li <li class="<%= 'active' if params[:order] == 'by_upper_bound' %>"> <%= link_to("按最高践行时段排序", jobs_path(:order => "by_upper_bound" )) %></li>
      </ul>

      <table class="table table-hover table-boldered table-striped">
        <thead>
          <tr>
            <th>概念名称</th>
            <th>践行城市</th>
            <th>践行时限</th>
            <th>发布时间</th>
            <% if !current_user || !current_user.is_admin? %>
            <th>申请践行</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @jobs.each do |job| %>
          <tr>
            <td><%= link_to(job.title, job_path(job)) %></td>
            <td><%= link_to(job.category_name, "/jobs/search?utf8=✓&q=" + job.category_name) %></td>
            <td>
              <span class="label label-default"><%= job.wage_lower_bound %>天 -
                <%= job.wage_upper_bound %>天</span>
            </td>
            <td><%= formatDate(job.created_at) %></td>
            <% if !current_user || !current_user.is_admin? %>
            <td><%= render 'resume_btn', :job => job %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= will_paginate @jobs %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <div class="container">
    <h1>
      新增概念
    </h1>
    <hr/>

    <%= simple_form_for @job do |f| %>
    <div class="form-group">
      <%= f.input :title, :label => "概念名称", input_html: { class: "form-control"} %>
      <%= f.input :description, :label => "概念内容", input_html: { class: "form-control"} %>
      <%= f.input :company_name, :label => "践行标准", input_html: { class: "form-control" rows="3"} %>
      <%= f.input :wage_lower_bound, :label => "最高践行时长", input_html: { class: "form-control"} %>
      <%= f.input :wage_upper_bound, :label => "最低践行时长", input_html: { class: "form-control"} %>
      <%= f.input :contact_email, :label => "联系邮箱", input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
    <% end %>
  </div>
</div>

app/views/jobs/search.html.erb
<div class="container">
  <div class="search-result">
    <%= link_to(jobs_path, class: "btn btn-success back-btn ") do  %>
    <span class="fa fa-arrow-left" style="margin-right: 10px;"></span>返回概念列表
    <% end %>

    <% if @jobs.length > 0 %>
    <table class="table table-hover table-boldered table-striped custab">
      <thead>
        <tr>
          <th>概念名称</th>
          <th>践行城市</th>
          <th>践行时限</th>
          <th>发布时间</th>
          <% if !current_user || !current_user.is_admin? %>
          <th>申请践行</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
        <tr>
          <td><%= link_to(job.title, job_path(job)) %></td>
          <td>
            <%= job.category_name %>
          </td>
          <td>
            <span class="label label-default"><%= job.wage_lower_bound %>天 -
              <%= job.wage_upper_bound %>天</span>
          </td>
          <td><%= formatDate(job.created_at) %></td>
          <% if !current_user || !current_user.is_admin? %>
          <td><%= render 'resume_btn', :job => job %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="text-center">
      <%= will_paginate @jobs %>
    </div>

  <% else %>
    <p class="empty-message">Sorry，没有搜到相关概念，我们将尽快更新概念，感谢关注！</p>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="col-md-12 show">
    <%= link_to(jobs_path, class: "btn btn-default back-btn") do  %>
    <span class="fa fa-arrow-left" style="margin-right: 10px;"></span>返回概念列表
    <% end %>
    <h2 class="job_title"><%= @job.title %></h2>

    <p class="info">
      <b>践行时长</b>
      <span class="salary">
        <span class="label label-success"><%= @job.wage_lower_bound %>天</span>
        -
        <span class="label label-success"><%= @job.wage_upper_bound %>天</span>
      </span>&nbsp

      <span>
        &nbsp<span class="fa fa-clock-o">&nbsp</span><%= formatDate(@job.created_at) %>
        发布</span>
    </p>

    <p class="send-resume">
      <%= render 'resume_btn', :job => @job %>
    </p>

    <hr>

    <p class="description-title">
      <strong>概念详情：</strong>
    </p>
    <p class="description"></p>
    <%= render_job_description(@job) %>
  </div>
</div>