config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs do
    collection do
      get :search
    end
    resources :resumes
  end

  namespace :account do
    resources :jobs
  end

  namespace :admin do
    namespace :account do
      resources :jobs do
        member do
          post :publish
          post :hide
        end

        resources :resumes
      end
    end
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
    resources :categories
  end
  root 'welcome#index'
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: { message: "请填写概念名称" }
  validates :description, presence: { message: "请填写概念描述" }
  validates :company_name, presence: { message: "请填写践行标准" }
  validates :category_name, presence: { message: "请选择践行城市" }
  validates :wage_upper_bound, presence: { message: "请填写最低践行时长" }
  validates :wage_lower_bound, presence: { message: "请填写最高践行时长" }
  validates :wage_lower_bound, numericality: { greater_than: 0, message: "最小践行天数必须＞0" }
  validates :wage_lower_bound, numericality: { less_than: :wage_upper_bound, message: "践行时段下限不能高于践行时段上限" }
  validates :contact_email, presence: { message: "请填写联系邮箱" }

# 最大薪资必须大于最小薪资

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  scope :publish, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }

  has_many :resumes
  belongs_to :category
  belongs_to :user

  has_many :job_relationships
  has_many :members, through: :job_relationships, source: :user
end

app/controllers/account/jobs_controller.rb
class Account::JobsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_is_not_admin

	def index
		@jobs = current_user.participated_jobs.paginate(:page => params[:page], :per_page => 10)
	end
end

app/controllers/admin/account/jobs_controller.rb
class Admin::Account::JobsController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :require_is_admin

  layout "admin"

  def index
    @jobs = current_user.jobs.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      redirect_to admin_jobs_path, alert: "概念已隐藏，无法查阅了，你想清楚就好！"
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "概念更新成功！这年头必须随时更新自己脑子里面的概念！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path, alert: "概念已删除了，你后悔吗？"
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :company_name, :wage_upper_bound, :wage_lower_bound, :contact_email, :category_name)
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :require_is_super_admin, only: [:new, :edit, ]

  layout "admin"

  def index
    @jobs = Job.all.recent.paginate(:page => params[:page], :per_page => 15)
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      redirect_to admin_account_jobs_path, alert: "概念已隐藏，无法查阅，你想清楚就好！"
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    if @job.save
      redirect_to admin_account_jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_account_jobs_path, notice: "概念更新成功！这年头必须随时更新自己脑子里面的概念！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_account_jobs_path, alert: "概念已删除，如果后悔赶紧做个提取练习试试！快去，我等你！"
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :company_name, :wage_upper_bound, :wage_lower_bound, :contact_email, :category_name)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_filter :validate_search_key, :only => [:search]

  def index
    @jobs = case params[:order]
            when 'by_lower_bound'
              Job.publish.order('wage_lower_bound').paginate(:page => params[:page], :per_page => 10)
            when 'by_upper_bound'
              Job.publish.order('wage_upper_bound').paginate(:page => params[:page], :per_page => 10)
            else
              Job.publish.recent.paginate(:page => params[:page], :per_page => 10)
            end
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "不好意思概念已隐藏！"
      redirect_to root_path
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path, notice: "当你看到这段文字时，代表着你成功升级了，但离财富自由还有100000光年，加油！"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path, alert: "恭喜你做了舍弃行为！这年头放弃安全感真的不容易啊！"
  end

  def search
    if @query_string.present?
      search_result = Job.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.paginate(:page => params[:page], :per_page => 15 )
      puts @jobs
    else
      @jobs = Job.publish.recent.paginate(:page => params[:page], :per_page => 10)
      puts @jobs
    end
  end

  private

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    { :title_or_description_or_contact_email_or_location_or_company_name_or_category_name_cont => query_string }
  end

  def job_params
    params.require(:job).permit(:title, :description, :company_name, :wage_upper_bound, :wage_lower_bound, :contact_email)
  end
end

app/helpers/account/jobs_helper.rb
module Account::JobsHelper
end

app/helpers/admin/account/jobs_helper.rb
module Admin::Account::JobsHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_description(job)
		simple_format(job.description)
	end
end

app/views/admin/jobs/_form.html.erb
<div class="form-box">
  <%= simple_form_for [:admin, @job]  do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "概念名称", input_html: { class: "form-control"}, placeholder: "注意力/落后/抱怨/贵人..." %>
    <%= f.input :description, :label => "概念描述", input_html: { class: "form-control"} %>
    <%= f.input :company_name, :label => "践行标准", input_html: { class: "form-control"} %>
    <% if @job.category_name? %>
    <%= f.input :category_name, :label => "践行城市", :collection => ["北京", "上海", "杭州", "纽约", "东京"], as: :radio_buttons, :checked => @job.category_name %>
  <% else %>
    <%= f.input :category_name, :label => "践行城市", :collection => ["北京", "上海", "杭州", "纽约", "东京"], as: :radio_buttons, :checked => "城市" %>
    <% end %>
    <%= f.input :wage_lower_bound, :label => '践行时限' do %>
    <%= f.input_field :wage_lower_bound, :as => :string, placeholder: '最低时长' %>
    天 ~
    <%= f.input_field :wage_upper_bound, :as => :string, placeholder: '最高时长' %>
    天
    <% end %>

    <%= f.input :contact_email, :label => "联系邮箱", input_html: { class: "form-control"} %>

  </div>
  <%= f.submit "提交", class: "btn btn-success", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

app/views/admin/jobs/_navbar.html.erb
<div class="container">
  <div class="nav-side-menu">
    <div class="brand"></div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
      <ul id="menu-content" class="menu-content collapse out">
        <li>
          <%= link_to(admin_jobs_path) do %>
          <i class="fa fa-list-alt fa-lg"></i>
          管理所有概念
          <% end %>
        </li>
        <li>
          <%= link_to(jobs_path) do %>
          <i class="fa fa-list fa-lg"></i>
          查看已发布概念
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/jobs/edit.html.erb
<div class="container">
  <h2>编辑概念</h2>

  <hr>

  <%= render "form" %>
</div>

app/views/admin/jobs/index.html.erb
<div class="container">
  <div class="group">
    <%= link_to("新增概念", new_admin_job_path, class: "btn btn-success pull-right") %>
  </div>

  <table class="table table-hover table-boldered table-striped custab">
    <thead>
      <tr>
        <th>概念名称</th>
        <th>收到践行申请数</th>
        <th>践行城市</th>
        <th>践行时限</th>
        <th>发布时间</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
      <tr>
        <td>
          <%= render_job_status(job) %>
          <%= link_to(job.title, job_path(job)) %>
        </td>
        <td>
          <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %>
        </td>
        <td>
          <%= job.category_name %>
        </td>
        <td>
          <span class="label label-default"><%= job.wage_lower_bound %>天 -
            <%= job.wage_upper_bound %>天</span>
        </td>
        <td><%= formatTime(job.created_at) %></td>
        <td>
          <%= link_to edit_admin_job_path(job), class: "btn btn-xs btn-info" do %>
          <span class="fa fa-pencil"></span>
          <% end %>

          <% if job.is_hidden %>
          <%= link_to publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success" do %>
          <span class="fa fa-eye"></span>发布<% end %>
        <% else %>
          <%= link_to hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning" do %>
          <span class="fa fa-eye-slash"></span><% end %>
          <% end %>

          <%= link_to admin_job_path(job), :method => :delete, :class => "btn btn-xs  btn-danger", :data => { :confirm => "Are you sure?" } do %>
          <span class="fa fa-trash"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= will_paginate @jobs %>
  </div>
</div>

app/views/admin/jobs/new.html.erb
<div class="container">
  <h2>发布概念</h2>

  <hr>

  <%= render "form" %>
</div>