config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs do
    collection do
      get :search
    end
    resources :resumes
  end

  namespace :account do
    resources :jobs
  end

  namespace :admin do
    namespace :account do
      resources :jobs do
        member do
          post :publish
          post :hide
        end

        resources :resumes
      end
    end
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
    resources :categories
  end
  root 'welcome#index'
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer id="footer">

  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <p>&copy; 2017 OUTPOST
          </p>
        </div>
        <div class="col-sm-6">
          <p class="pull-right">Design by
            <a href="https://farm3.staticflickr.com/2833/34122904572_2754e03040_o.png">GUYAN</a>
          </p>
        </div>
      </div>
    </div>
  </div>

</footer>

app/views/common/_navbar.html.erb
<% if current_page?('jobss_path') %>
<nav class="navbar navbar-default transparent" role="navigation" id="navbar">
<% else %>
  <nav class="main-nav" role="navigation">
    <% end %>
    <div class="container">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="/"><img src="https://farm4.staticflickr.com/3954/34101927312_6306961d23_o.png"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('首页', root_path) %></li>
            <li><%= link_to('概念列表', jobs_path) %></li>
            <% if !current_user %>
            <li><%= link_to("注册", new_user_registration_path) %></li>
            <li><%= link_to("登录", new_user_session_path) %></li>
          <% else %>
            <% if current_user && current_user.admin? %>
            <li><%= link_to("后台管理", admin_account_jobs_path) %></li>
          <% else %>
            <li><%= link_to("已投递申请的概念", account_jobs_path) %></li>
            <% end %>
            <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</div>
</nav>